# Generated by Django 3.1.7 on 2021-07-30 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20210730_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopuser',
            old_name='activation_key_expires',
            new_name='activation_key_created',
        ),
    ]
