# Generated by Django 3.2.5 on 2021-07-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20210730_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
